// <auto-generated />
using System;
using Elsa.Dashboard.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elsa.Dashboard.Web.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20200803075836_AddDemo")]
    partial class AddDemo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Elsa.Dashboard.Web.Data.Approve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AuditStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("CorrelateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WfActivityInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("WfInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Approves");
                });

            modelBuilder.Entity("Elsa.Dashboard.Web.Data.LeaveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApproveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproveId");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("Elsa.Dashboard.Web.Data.LeaveRecord", b =>
                {
                    b.HasOne("Elsa.Dashboard.Web.Data.Approve", "Approve")
                        .WithMany()
                        .HasForeignKey("ApproveId");
                });
#pragma warning restore 612, 618
        }
    }
}
